controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

add_to_cart:
  path: /add-to-cart/{id}
  controller: App\Controller\CartController::addToCart
  methods: [POST]
